# Generated by Django 5.0.3 on 2024-03-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.BigIntegerField()),
                ('Xray', models.FileField(null=True, upload_to='e_sign/', verbose_name='')),
                ('result', models.CharField(blank=True, choices=[('Fractured', 'Fractured'), ('Not Fractured', 'Not Fractured')], max_length=30, null=True)),
                ('description_fractured', models.CharField(blank=True, help_text='Enter the description if the result is Fractured', max_length=1000, null=True)),
                ('description_not_fractured', models.CharField(blank=True, help_text='Enter the description if the result is Not Fractured', max_length=1000, null=True)),
            ],
        ),
    ]
